events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    resolver 127.0.0.11 valid=10s;
    resolver_timeout 5s;
    
    # Optimizaciones
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;
        
        # Ruta donde están tus archivos PHP dentro del contenedor
        root /var/www/html/public;
        index index.php;

        # 1. Intentar servir archivos reales primero, si no, pasar a PHP
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # 2. Configuración específica para procesar archivos .php
        location ~ \.php$ {
            # Debe coincidir con el nombre del servicio en docker-compose
            set $php_upstream frontend:9000;
            fastcgi_pass $php_upstream; 
            fastcgi_index index.php;
            include fastcgi_params;
            # Esta línea es vital para que PHP sepa qué archivo ejecutar
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # 3. Ruta para API REST
        location = /api {
            return 301 /api/;
        }

        location ^~ /api/ {
            set $api_upstream api:8000;
            proxy_pass http://$api_upstream$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Original-URI $request_uri;
            proxy_redirect off;
            proxy_buffering off;
            break;
        }

        # 4. Ruta para phpMyAdmin 
        location = /phpmyadmin {
            return 301 /phpmyadmin/;
        }

        location ^~ /phpmyadmin/ {
            set $pma_upstream phpmyadmin:80;
            proxy_pass http://$pma_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Prefix /phpmyadmin;
            proxy_redirect off;
            proxy_buffering off;
            
            # IMPORTANTE: Detener el procesamiento de otras reglas aquí
            break; 
        }

        # Health check
        location /health {
            access_log off;
            return 200 "OK\n";
        }
    }
}